import { SLICE_NAME } from '@config/type';

export const LOGIN = SLICE_NAME.AUTHENTICATION + 'LOGIN';
export const FORGOT_PWD = SLICE_NAME.AUTHENTICATION + 'FORGOT_PWD';
export const CHECK_PWD = SLICE_NAME.AUTHENTICATION + 'CHECK_PWD';
export const CHANGE_PWD = SLICE_NAME.AUTHENTICATION + 'CHANGE_PWD';
export const CHANGE_PWD_WITHOUT_TOKEN = SLICE_NAME.AUTHENTICATION + 'CHANGE_PWD_WITHOUT_TOKEN';
export const VERIFY_OTP = SLICE_NAME.AUTHENTICATION + 'VERIFY_OTP';
export const VERIFY_OTP_RESET = SLICE_NAME.AUTHENTICATION + 'VERIFY_OTP_RESET';
export const UPDATE_PROFILE = SLICE_NAME.AUTHENTICATION + 'UPDATE_PROFILE';
export const DETAIL_PROFILE = SLICE_NAME.AUTHENTICATION + 'DETAIL_PROFILE';
export const UPDATE_STATUS_PROFILE = SLICE_NAME.AUTHENTICATION + 'UPDATE_STATUS_PROFILE';
export const UPDATE_WORKING_TIME = SLICE_NAME.AUTHENTICATION + 'UPDATE_WORKING_TIME';
export const UPDATE_WORKING_LOCATION= SLICE_NAME.AUTHENTICATION + 'UPDATE_WORKING_LOCATION';



export const GET_PROVINCES = SLICE_NAME.AUTHENTICATION + 'GET_PROVINCES';
export const GET_DISTRICS = SLICE_NAME.AUTHENTICATION + 'GET_DISTRICS';
