import { SLICE_NAME } from '@config/type';

export const GET_LIST = SLICE_NAME.ORDER + 'GET_LIST';
export const GET_ORDER = SLICE_NAME.ORDER + 'GET_ORDER';
export const GET_REQUEST_ORDER = SLICE_NAME.ORDER + 'GET_REQUEST_ORDER';
export const REJECT_ORDER = SLICE_NAME.ORDER + 'REJECT_ORDER';
export const SIGN_CONTRACT_ORDER = SLICE_NAME.ORDER + 'SIGN_CONTRACT_ORDER';
export const REQUEST_PAYMENT_ORDER = SLICE_NAME.ORDER + 'REQUEST_PAYMENT_ORDER';
export const PAID_CONFIRMED_ORDER = SLICE_NAME.ORDER + 'PAID_CONFIRMED_ORDER';
export const MATCHING_ORDER = SLICE_NAME.ORDER + 'MATCHING_ORDER';
