import { SLICE_NAME } from '@config/type';

export const GET_REPORT_DETAIL = SLICE_NAME.WORKPLACE + 'GET_REPORT_DETAIL';
export const GET_SUPPLIES = SLICE_NAME.WORKPLACE + 'GET_SUPPLIES';
export const GET_SUPPLIES_DETAIL = SLICE_NAME.WORKPLACE + 'GET_SUPPLIES_DETAIL';
export const GET_DETAIL_STATICALS = SLICE_NAME.WORKPLACE + 'GET_DETAIL_STATICALS';
export const GET_DETAIL_PERFORMANCE = SLICE_NAME.WORKPLACE + 'GET_DETAIL_PERFORMANCE';
export const UPDATE_SUPPLIES = SLICE_NAME.WORKPLACE + 'UPDATE_SUPPLIES';
export const UPDATE_WORKING_LOCATION = SLICE_NAME.WORKPLACE + 'UPDATE_WORKING_LOCATION';
export const GET_PROVINCES = SLICE_NAME.WORKPLACE + 'GET_PROVINCES';
export const GET_DISTRICS = SLICE_NAME.WORKPLACE + 'GET_DISTRICS';
